# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-10 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resumen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_resumen', models.CharField(max_length=30)),
                ('titulo_resumen', models.CharField(max_length=150)),
                ('texto_resuemen', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UrlResumen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=400)),
            ],
        ),
        migrations.AddField(
            model_name='resumen',
            name='url_resumen',
            field=models.ManyToManyField(to='resumen.UrlResumen'),
        ),
    ]
