# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-10 17:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resumen', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumen',
            name='url_resumen',
        ),
        migrations.AddField(
            model_name='resumen',
            name='url_resumen',
            field=models.OneToOneField(blank=True, default=b'', on_delete=django.db.models.deletion.CASCADE, to='resumen.UrlResumen'),
        ),
    ]
