# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-10 18:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resumen', '0003_auto_20160310_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagsResumen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='resumen',
            name='tag_resumen',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='resumen.TagsResumen', unique=True),
        ),
    ]
