# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-10 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumen', '0005_auto_20160310_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumen',
            name='status',
            field=models.CharField(blank=True, max_length=110, null=True, verbose_name=b'Status'),
        ),
    ]
