# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-12 15:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listas', '0001_initial'),
        ('resumen', '0006_resumen_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoticiaResumen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_noticia_resumen', models.CharField(max_length=200, verbose_name=b'Titulo de Resumen')),
                ('cuerpo_noticia_resumen', models.TextField(default=b'', verbose_name=b'Cuerpo del resumen')),
                ('tag_resumen', models.CharField(choices=[(b'REG', b'Regionales'), (b'NAC', b'Nacionales'), (b'INT', b'Internacionales'), (b'ECO', b'Economia'), (b'DEP', b'Deporte'), (b'SUC', b'Sucesos')], default=b'', max_length=30, verbose_name=b'Etiqueta')),
                ('url', models.TextField(verbose_name=b'URLs')),
            ],
            options={
                'ordering': ('tag_resumen', 'titulo_noticia_resumen'),
                'verbose_name_plural': 'Agregar Resumen de Noticia',
            },
        ),
        migrations.AlterModelOptions(
            name='resumen',
            options={'ordering': ('fecha', 'status', 'enviadopor'), 'verbose_name_plural': 'Agregar Resumen'},
        ),
        migrations.RemoveField(
            model_name='resumen',
            name='tag_resumen',
        ),
        migrations.RemoveField(
            model_name='resumen',
            name='texto_resumen',
        ),
        migrations.RemoveField(
            model_name='resumen',
            name='titulo_resumen',
        ),
        migrations.RemoveField(
            model_name='resumen',
            name='url_resumen',
        ),
        migrations.AddField(
            model_name='resumen',
            name='cuerpo_mensaje',
            field=models.TextField(default=b'', verbose_name=b'Cuerpo el mensaje'),
        ),
        migrations.AddField(
            model_name='resumen',
            name='enviadopor',
            field=models.CharField(default=b'', max_length=50, verbose_name=b'Enviado por:'),
        ),
        migrations.AddField(
            model_name='resumen',
            name='lista',
            field=models.ManyToManyField(to='listas.Listas'),
        ),
        migrations.AddField(
            model_name='resumen',
            name='titulo_mensaje',
            field=models.CharField(default=b'', max_length=150, verbose_name=b'Titulo'),
        ),
        migrations.DeleteModel(
            name='TagsResumen',
        ),
        migrations.DeleteModel(
            name='UrlResumen',
        ),
        migrations.AddField(
            model_name='noticiaresumen',
            name='resumenes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumen.Resumen'),
        ),
    ]
