# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-12 16:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resumen', '0007_auto_20160312_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticiaresumen',
            name='resumenes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resumen.Resumen', verbose_name=b'Resumen'),
        ),
    ]
