# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-12 17:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumen', '0008_auto_20160312_1137'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noticiaresumen',
            options={'ordering': ('tag_noticia_resumen', 'titulo_noticia_resumen'), 'verbose_name_plural': 'Agregar Resumen de Noticia'},
        ),
        migrations.RenameField(
            model_name='noticiaresumen',
            old_name='tag_resumen',
            new_name='tag_noticia_resumen',
        ),
        migrations.RenameField(
            model_name='noticiaresumen',
            old_name='url',
            new_name='url_noticia_resumen',
        ),
    ]
