# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-12 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumen', '0009_auto_20160312_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticiaresumen',
            name='titulo_noticia_resumen',
            field=models.CharField(max_length=350, verbose_name=b'Titulo de Resumen'),
        ),
    ]
