# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-13 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumen', '0010_auto_20160312_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticiaresumen',
            name='status',
            field=models.CharField(blank=True, max_length=110, null=True, verbose_name=b'Status'),
        ),
    ]
