# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-13 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumen', '0011_noticiaresumen_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumen',
            name='tipo_envio',
            field=models.CharField(choices=[(b'Automatico', b'Automatico'), (b'Programado', b'Programado')], default=b'', max_length=20, verbose_name=b'Tipo de envio'),
        ),
    ]
