# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-13 14:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumen', '0012_resumen_tipo_envio'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticiaresumen',
            name='enviadopor_noticia_resumen',
            field=models.CharField(default=b'', max_length=50, verbose_name=b'Enviado por:'),
        ),
        migrations.AddField(
            model_name='noticiaresumen',
            name='fecha_noticia_resumen',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
