# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-14 17:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avances', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnlaceDiarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(verbose_name=b'Enlace de noticia')),
                ('diario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avances.Diarios')),
            ],
        ),
        migrations.AlterModelOptions(
            name='noticias',
            options={'ordering': ('status',), 'verbose_name_plural': 'Agregar noticias para avances'},
        ),
        migrations.RemoveField(
            model_name='noticias',
            name='url',
        ),
        migrations.AddField(
            model_name='enlacediarios',
            name='noticia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avances.Noticias'),
        ),
    ]
