# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-14 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avances', '0003_auto_20160314_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enlacediarios',
            name='url',
            field=models.URLField(verbose_name=b'Enlace de noticia'),
        ),
    ]
