# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-14 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avances', '0004_auto_20160314_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avances',
            name='titulo_mensaje',
            field=models.CharField(max_length=1000, verbose_name=b'Titulo'),
        ),
        migrations.AlterField(
            model_name='noticias',
            name='titulo_noticia',
            field=models.CharField(max_length=1000, verbose_name=b'Titulo'),
        ),
    ]
