# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-15 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avances', '0005_auto_20160314_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticias',
            name='antetitulo_noticia',
            field=models.CharField(blank=True, max_length=500, verbose_name=b'Antetitulo'),
        ),
        migrations.AlterField(
            model_name='noticias',
            name='hora',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='noticias',
            name='titulo_noticia',
            field=models.CharField(max_length=500, verbose_name=b'Titulo'),
        ),
    ]
