# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-11 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avances', '0007_remove_noticias_diarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='enlacediarios',
            name='tag_noticia',
            field=models.CharField(choices=[(b'REG', b'Regionales'), (b'NAC', b'Nacionales'), (b'INT', b'Internacionales'), (b'ECO', b'Economia'), (b'DEP', b'Deporte'), (b'SUC', b'Sucesos')], default=b'', max_length=30, verbose_name=b'Etiqueta'),
        ),
    ]
