# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 16:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archivos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.FileField(blank=True, null=True, upload_to=b'archivos_boletin/')),
            ],
            options={
                'ordering': ('documento',),
                'verbose_name_plural': 'Archivos de los boletines',
            },
        ),
        migrations.CreateModel(
            name='Boletines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, default=datetime.datetime.now)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('tipo_envio', models.CharField(choices=[(b'Automatico', b'Automatico'), (b'Programado', b'Programado')], default=b'A', max_length=20, verbose_name=b'Tipo de envio')),
                ('status', models.CharField(blank=True, max_length=110, null=True, verbose_name=b'Status')),
                ('titulo_mensaje', models.CharField(max_length=110, verbose_name=b'Titulo')),
                ('cuerpo_mensaje', models.TextField(verbose_name=b'Cuerpo del mensaje')),
                ('enviadopor', models.CharField(max_length=50, verbose_name=b'Enviado por:')),
                ('listas', models.ManyToManyField(to='listas.Listas')),
            ],
            options={
                'ordering': ('fecha', 'tipo_envio', 'titulo_mensaje', 'status', 'enviadopor'),
                'verbose_name_plural': 'Agregar boletin',
            },
        ),
        migrations.AddField(
            model_name='archivos',
            name='boletines',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='boletines.Boletines', verbose_name=b'Boletines'),
        ),
    ]
