# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_lista', models.CharField(choices=[(b'Boletin', b'Boletin'), (b'Avance', b'Avance'), (b'Resumen', b'Resumen'), (b'Primeras planas', b'Primeras planas'), (b'Columna de opini\xc3\xb3n', b'Columna de opini\xc3\xb3n'), (b'Informe de Televisi\xc3\xb3n', b'Informe de Televisi\xc3\xb3n')], default=b'Boletin', max_length=20, verbose_name=b'Tipo de lista')),
                ('nombre_lista', models.CharField(max_length=100, unique=True, verbose_name=b'Nombre de la lista')),
                ('descripcion_lista', models.TextField(max_length=1000, verbose_name=b'Descripcion de la lista')),
            ],
            options={
                'ordering': ('nombre_lista',),
                'verbose_name_plural': 'Agregar Listas',
            },
        ),
    ]
