# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_contacto', models.CharField(max_length=50, verbose_name=b'Nombre y apellido del contacto')),
                ('institucion', models.CharField(max_length=50, verbose_name=b'Institucion')),
                ('telefono', models.CharField(blank=True, max_length=50, verbose_name=b'Telefono')),
                ('correo', models.EmailField(blank=True, max_length=254, verbose_name=b'Correo')),
                ('listas', models.ManyToManyField(to='listas.Listas')),
            ],
            options={
                'ordering': ('nombre_contacto',),
                'verbose_name_plural': 'Agregar Contactos',
            },
        ),
    ]
